In [2]:
import numpy as np
from scipy.linalg import svd

In [3]:
A=np.array([[1,1,1],[1,1,1]])
AT=np.transpose(A)
ATA=np.dot(AT,A)

In [4]:
print(A)

[[1 1 1]
 [1 1 1]]


In [38]:
val_p, vec_p = np.linalg.eig(ATA)
V=vec_p
VT=np.transpose(V)
S_1=np.sqrt(val_p[2])
#S_1
print("Autovalores:", val_p)
print("Vector de características:", vec_p)

Autovalores: [-4.4408921e-16  6.0000000e+00  0.0000000e+00]
Vector de características: [[-0.81649658  0.57735027  0.        ]
 [ 0.40824829  0.57735027 -0.70710678]
 [ 0.40824829  0.57735027  0.70710678]]


In [25]:
U, S, VT=svd(A)
print(U)
print(S)
print(VT)

[[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]
[2.44948974e+00 1.11022302e-16]
[[-0.57735027 -0.57735027 -0.57735027]
 [-0.81649658  0.40824829  0.40824829]
 [ 0.         -0.70710678  0.70710678]]
